---
# This playbook deploys my favourite packages in my workstation.

- hosts: all
  become: true
  connection: local
  gather_facts: no
  vars_files:
    - vars/default.yml
  roles:
    - basic
    - security
    - development
