---
# variables

basic_packages:
  - apt-transport-https
  - htop
  - python-pip
  - rcconf
  - tmux
  - tree
  - vim

development_jad_installer: 'https://varaneckas.com/jad/jad158e.linux.static.zip'
