---
# Clean up, based largely on https://l3net.wordpress.com/2013/02/08/ubuntu-cleanup/

- name: Uninstall packages
  apt: pkg={{ item }} state=absent
  with_items:
   - apt-xapian-index
   - click
   - colord
   - deja-dup
   - gir1.2-ubuntuoneui-3.0
   - libubuntuoneui-3.0-1
   - libzeitgeist-1.0-1
   - python-ubuntuone-client
   - python-ubuntuone-control-panel
   - python-ubuntuone-storageprotocol
   - python-zeitgeist
   - rhythmbox-plugin-zeitgeist
   - rhythmbox-ubuntuone
   - ubuntuone-client
   - ubuntuone-client-gnome
   - ubuntuone-control-panel
   - ubuntuone-couch
   - ubuntuone-installer
   - zeitgeist
   - zeitgeist-core
   - zeitgeist-datahub

- name: Stop services
  systemd: name={{ item }} state=stopped enabled=no
  with_items:
    - apport
    - avahi-daemon
    - brltty
    - cups
    - cups-browsed
    - speech-dispatcher

- name: Disable zeitgeist access to its DB
  file:
    path: /home/kinow/.local/share/zeitgeist/activity.sqlite
    state: file
    mode: 0100

- name: Disable avahi-daemon completely 1
  copy:
    content: |
      start on (never
         and filesystem
          and started dbus)
      stop on stopping dbus
    dest: /etc/init/avahi-daemon.conf
    backup: yes
  run_once: yes
  delegate_to: localhost

- name: Disable avahi-daemon completely 2
  copy:
    content: |
      #!/bin/sh
      exit 0
    dest: /etc/network/if-up.d/avahi-autoipd
    backup: yes
  run_once: yes
  delegate_to: localhost

- name: Disable avahi-daemon completely 2
  copy:
    content: |
      #!/bin/sh
      exit 0
    dest: /etc/network/if-up.d/avahi-daemon
    backup: yes
  run_once: yes
  delegate_to: localhost
