---
- name: Install basic tools
  action: apt pkg={{item}} state=installed
  with_items:
    {{ packages }}

- name: Install communication tools
  action: apt pkg={{item}} state=installed
  with_items:
   - thunderbird
   - xchat-gnome

- include: roles/basic/tasks/xfce.yml
- include: roles/basic/tasks/wallpaper.yml
- include: roles/basic/tasks/chrome.yml
