---
- name: Install basic tools
  apt: update_cache=yes cache_valid_time=3600 pkg={{ item }} state=present # won't update if done under an hour ago
  with_items:
    "{{ basic_packages }}"

- name: Install communication tools
  apt: update_cache=yes cache_valid_time=3600 pkg={{ item }} state=present # won't update if done under an hour ago
  with_items:
   - thunderbird
   - xchat-gnome

- include: roles/basic/tasks/xfce.yml
- include: roles/basic/tasks/wallpaper.yml
- include: roles/basic/tasks/chrome.yml
