---
- name: Install basic tools
  apt: update_cache=yes cache_valid_time=3600 pkg={{ item }} state=present # won't update if done under an hour ago
  with_items:
    "{{ basic_packages }}"

- name: Install communication tools
  apt: update_cache=yes cache_valid_time=3600 pkg={{ item }} state=present # won't update if done under an hour ago
  with_items:
   - thunderbird
   - xchat-gnome

- name: Install multimedia
  apt: update_cache=yes cache_valid_time=3600 pkg={{ item }} state=present # won't update if done under an hour ago
  with_items:
   - vlc

- name: Install games
  apt: update_cache=yes cache_valid_time=3600 pkg={{ item }} state=present # won't update if done under an hour ago
  with_items:
   - wesnoth

- import_tasks: xfce.yml
- import_tasks: chrome.yml
- import_tasks: cleanup.yml
- import_tasks: japanese.yml
- import_tasks: virtualbox.yml
