---
# Install Anaconda Python3

- name: Checking if Anaconda is already installed
  stat: 
    path: '/home/kinow/Development/python/anaconda3'
  register: anaconda_installed

- name: Downloading Anaconda Binaries
  get_url:
    url: '{{ development_anaconda_download_url }}'
    dest: '/tmp/{{ development_anaconda_file_name }}'
  when: anaconda_installed.stat.exists != True

- name: Batch install Anaconda
  shell: /bin/bash /tmp/{{ development_anaconda_file_name }} -b -f -p /home/kinow/Development/python/anaconda3
  when: anaconda_installed.stat.exists != True

- name: Set permissions for folder
  file:
    path: /home/kinow/Development/python/anaconda3
    owner: kinow
    group: kinow
    state: directory
    recurse: yes

- name: Create source file
  copy:
    content: |
      #!/bin/bash

      . /home/kinow/Development/python/anaconda3/etc/profile.d/conda.sh
    dest: /home/kinow/Development/python/sa3.sh
    backup: no
    owner: kinow
    group: kinow
  run_once: yes
