---
# Install git

- name: Install git
  action: apt pkg={{item}} state=present
  with_items:
    - gitk
    - git
    - git-svn
  tags: git

- name: Setup default git configuraiton
  become: yes
  become_user: kinow
  git_config:
    name="{{ item.name }}"
    scope=global
    value="{{ item.value }}"
  with_items:
    - {name: "user.name",  value: "Bruno P. Kinoshita", scope: "global" }
    - {name: "user.email", value: "kinow@users.noreply.github.com", scope: "global" }
    - {name: "ui.color", value: "True", scope: "global" }
    - {name: "core.editor", value: "vim", scope: "global" }
    - {name: "push.default", value: "simple", scope: "global" }
    - {name: "core.autocrlf", value: "input", scope: "global" }
    - {name: "alias.git", value: "!exec git", scope: "global" }
