---
# Install Java development environment
# IDE is not covered

- name: Add webupd repo
  become_method: sudo
  apt_repository: repo='ppa:webupd8team/java'

- name: Deal with licence
  become_method: sudo
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Java
  become_method: sudo
  apt: pkg={{item}} state=installed
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default

- name: Install other Java projects
  become_method: sudo
  apt: pkg={{item}} state=installed
  with_items:
    - ant
    - ant-contrib
    - gradle
    - javacc
    # to fix eclipse crashing saying it cannot find MOZILLA_FIVE_HOME
    - libwebkitgtk-1.0-0
