---
# Install Java development environment
# IDE is not covered

- name: add webupd repo
  become: True
  become_method: sudo
  apt_repository: repo='ppa:webupd8team/java'

- name: deal with licence
  become: True
  become_method: sudo
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: install Java
  become: True
  become_method: sudo
  apt: pkg={{item}} state=installed
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default

- name: install other Java projects
  become: True
  become_method: sudo
  apt: pkg={{item}} state=installed
  with_items:
    - maven
    - ant
    - ant-contrib

