---
# Install development tools, and configure development environments
- name: Create workspace directories
  action: file path={{item}} state=directory owner=kinow mode=0700
  with_items:
    - '/home/kinow/bin'
    - '/home/kinow/Development'
    - '/home/kinow/Development/java/workspace'
    - '/home/kinow/Development/java/apache'
    - '/home/kinow/Development/java/biouno'
    - '/home/kinow/Development/java/jenkins'
    - '/home/kinow/Development/java/jena'
    - '/home/kinow/Development/python/workspace'
    - '/home/kinow/Development/javascript/workspace'
    - '/home/kinow/Development/php/workspace'
    - '/home/kinow/Development/cpp/workspace'
    - '/home/kinow/Development/ansible/workspace'
    - '/home/kinow/Development/shell/workspace'
    - '/home/kinow/Development/r/workspace'
    - '/home/kinow/Development/ruby/workspace'
  tags:
    - development
    - java

# --- Development repositories

- name: Install UbuntuGIS repository
  apt_repository:
    repo: 'ppa:ubuntugis/ppa'
  tags:
    - development
    - gis

# --- Development packages

- name: Install base development packages and headers
  action: apt pkg={{item}} state=present
  with_items:
    - build-essential
    - unzip
    - p7zip-full
    - curl
    - xz-utils
    - cpio
    # next three for python piecrust module
    - libffi-dev
    - cl-cffi
    - ghp-import
    # for screen recording, creating GIF's, ...
    - byzanz
    - subversion
    # shellscript static analyzer
    - shellcheck
    # image processing
    - libimage-exiftool-perl
    - libgdal1-dev
    - libproj-dev
    - jhove
    # static site generators
    - jekyll
    # pdf
    - wkhtmltopdf
  tags: development

# --- Other packages

# Copy Eclipse Workspace
- name: Install cpew
  get_url:
    url: https://raw.githubusercontent.com/kinow/cpew/master/cpew
    dest: /home/kinow/bin/cpew
    mode: 0750
  tags:
    - development
    - java

# Byzanz Record GUI
- name: Install byzanz-gui
  get_url:
    url: https://raw.githubusercontent.com/rhcarvalho/byzanz-gui/master/byzanz-gui
    dest: /home/kinow/bin/byzanz-gui
    mode: 0750
  tags:
    - development

- import_tasks: roles/development/tasks/git.yml
- import_tasks: roles/development/tasks/sublime.yml
- import_tasks: roles/development/tasks/java.yml
- import_tasks: roles/development/tasks/maven.yml
- import_tasks: roles/development/tasks/anaconda.yml
- import_tasks: roles/development/tasks/r.yml
- import_tasks: roles/development/tasks/docker.yml
- import_tasks: roles/development/tasks/php.yml
- import_tasks: roles/development/tasks/scala.yml
- import_tasks: roles/development/tasks/cv.yml
- import_tasks: roles/development/tasks/gis.yml
- import_tasks: roles/development/tasks/nodejs.yml
- import_tasks: roles/development/tasks/ruby.yml
- import_tasks: roles/development/tasks/security.yml
- import_tasks: roles/development/tasks/vim.yml
