---
# Install development tools, and configure development environments
- name: Create workspace directories
  action: file path={{item}} state=directory
  with_items:
    - '/home/kinow/bin'
    - '/home/kinow/Development'
    - '/home/kinow/Development/java/workspace'
    - '/home/kinow/Development/java/apache'
    - '/home/kinow/Development/java/biouno'
    - '/home/kinow/Development/java/jenkins'
    - '/home/kinow/Development/java/jena'
    - '/home/kinow/Development/python/workspace'
    - '/home/kinow/Development/javascript/workspace'
    - '/home/kinow/Development/php/workspace'
    - '/home/kinow/Development/cpp/workspace'
    - '/home/kinow/Development/ansible/workspace'
    - '/home/kinow/Development/shell/workspace'

# --- Development packages

- name: Install base development packages and headers
  action: apt pkg={{item}} state=installed
  become: True
  become_method: sudo
  with_items:
    - build-essential
    - unzip
    - p7zip-full
    - curl
    - xz-utils
    - cpio
    # For screen recording, creating GIF's, ...
    - byzanz
    - gitk

# --- Other packages

# Copy Eclipse Workspace
- name: Install cpew
  get_url:
    url: https://raw.githubusercontent.com/kinow/cpew/master/cpew
    dest: /home/kinow/bin/cpew
    mode: 0750

# Byzanz Record GUI
- name: Install byzanz-gui
  get_url:
    url: https://raw.githubusercontent.com/rhcarvalho/byzanz-gui/master/byzanz-gui
    dest: /home/kinow/bin/byzanz-gui
    mode: 0750

# Sublime text

# Install Java development environment
# IDE is not covered

- name: add webupd repo
  become: True
  become_method: sudo
  apt_repository: repo='ppa:webupd8team/sublime-text-3'

- name: install Sublime Text 3
  become: True
  become_method: sudo
  apt: pkg={{item}} state=installed
  with_items:
    - sublime-text-installer

- include: roles/development/tasks/sublime.yml

- include: roles/development/tasks/java.yml

