---
# Install Apache Maven

- name: Checking if Maven is already installed
  stat: 
    path: '/opt/apache-maven-{{ development_maven_version }}'
  register: maven_installed

- name: Downloading Maven Binaries
  get_url:
    url: '{{ development_maven_download_url }}'
    dest: '/tmp/{{ development_maven_file_name }}'
  when: maven_installed.stat.exists != True

- name: Unarchive Maven Binaries
  unarchive:
    src: '/tmp/{{ development_maven_file_name }}'
    dest: '/opt'
    copy: no
  when: maven_installed.stat.exists != True

- name: Create mvn link
  file:
    src: '/opt/apache-maven-{{ development_maven_version }}/bin/mvn'
    dest: '/home/kinow/bin/mvn'
    state: link
