---
# Install prolog
# https://github.com/fnogatz/swivm

- name: Install prolog
  action: apt pkg={{item}} state=present
  with_items:
    - autoconf
    - make
    - libgmp-dev
    - libxt-dev
    - libjpeg-dev
    - libxpm-dev
    - libxft-dev
    - libdb-dev
    - libssl-dev
    - unixodbc-dev
    - libarchive-dev
    - swi-prolog-java
  tags: prolog